# Explore here
El objetivo del proyecto es descubrir la probabilidad de que una persona gane más de 50K anules a sus 40 años a través de un sistema de recomendación.

# Importar datos y análisis superficial

In [60]:
# Your code here
import pandas as pd 

ruta = 'https://breathecode.herokuapp.com/asset/internal-link?id=2326&path=adult-census-income.csv'
df = pd.read_csv(ruta)

df.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K

In [61]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  str
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  str
 4   education.num   32561 non-null  int64
 5   marital.status  32561 non-null  str
 6   occupation      32561 non-null  str
 7   relationship    32561 non-null  str
 8   race            32561 non-null  str
 9   sex             32561 non-null  str
 10  capital.gain    32561 non-null  int64
 11  capital.loss    32561 non-null  int64
 12  hours.per.week  32561 non-null  int64
 13  native.country  32561 non-null  str
 14  income          32561 non-null  str
dtypes: int64(6), str(9)
memory usage: 3.7 MB

In [62]:
df.shape

(32561, 15)

In [63]:
df.describe()

,age,fnlwgt,education.num,capital.gain,capital.loss,hours.per.week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

Tenemos un set de datos con 15 variables y 32561 registros.

No hay nulos.

# Limpieza de datos

In [64]:
# como no hay nulos, voy a revisar duplicados
df.duplicated().sum()

np.int64(24)

In [65]:
# elimino los 24 duplicados
df.drop_duplicates(inplace=True)

/tmp/ipykernel_1250/1693657722.py:2: Pandas4Warning: The inplace keyword in DataFrame.drop_duplicates is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  df.drop_duplicates(inplace=True)

In [66]:
# en las categoricas se pone '?' cuando se desconoce la informacion para no dejar nulo el dato, vamos a cargarnos esas filas
# si hay '?' dejamos el dato como nulo
df.replace("?", pd.NA, inplace=True)

print("nulos " , df.isnull().sum())
print("s " , df.shape)

# como ahora sí que hay nulos, puedo pasar el dropna y se los cargará
df.dropna(inplace = True)

nulos  age                  0
workclass         1836
fnlwgt               0
education            0
education.num        0
marital.status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital.gain         0
capital.loss         0
hours.per.week       0
native.country     582
income               0
dtype: int64
s  (32537, 15)

/tmp/ipykernel_1250/1014223894.py:9: Pandas4Warning: The inplace keyword in DataFrame.dropna is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  df.dropna(inplace = True)

In [67]:
print("nulos " , df.isnull().sum())
print("s " , df.shape)

nulos  age               0
workclass         0
fnlwgt            0
education         0
education.num     0
marital.status    0
occupation        0
relationship      0
race              0
sex               0
capital.gain      0
capital.loss      0
hours.per.week    0
native.country    0
income            0
dtype: int64
s  (30139, 15)

In [68]:
df.income.unique()

<StringArray>
['<=50K', '>50K']
Length: 2, dtype: str

Vamos a crear la variable objetivo a partir de aquellos donde income valga >50K

In [69]:
df.income.value_counts()

income
<=50K    22633
>50K      7506
Name: count, dtype: int64

In [70]:
df['high_income'] = (df['income'] == '>50K').astype(int)# 1 si cobra mas de 50k, 0 si no

In [71]:
df.high_income.value_counts()

high_income
0    22633
1     7506
Name: count, dtype: int64

# Split en test y train, entrenamiento del modelo

In [ ]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

# a partir de aqui tuve que tirar de solucion, mi forma de transformar los datos estaba siendo mas caotica y bastante mas larga que la
# de la solucion 


# variables predictoras y objetivo
predictoras = ['age', 'education', 'marital.status', 'occupation', 'hours.per.week', 'sex', 'native.country']
X = df[predictoras]
y = df['high_income']

# listas con la division de predictoras en numericas y categoricas
predictoras_numericas = ['age', 'hours.per.week']
predictoras_categoricas = ['education', 'marital.status', 'occupation', 'sex', 'native.country']

# transformadores para escalar / codificar datos
transformador_numerico = StandardScaler() # escala numericas
transformador_categorico = OneHotEncoder(handle_unknown='ignore') # transforma categoricas a binario, si no puede codificar pasa a la siguiente

#  creamos el preprocesador, que aplicara los transformadores a las listas de columnas que definimos previamente
preprocessor = ColumnTransformer(
    transformers=[("num", transformador_numerico, predictoras_numericas),
        ("cat", transformador_categorico, predictoras_categoricas) ]
)

In [73]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

# modelo a partir de pipeline: primero se aplica el preprocesador, luego clasificacion con un modelo de regresion logistica
model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(max_iter=1000))
])

# datasets y entrenamiento
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['age', 'hours.per.week']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['education',
                                                   'marital.status',
                                                   'occupation', 'sex',
                                                   'native.country'])])),
                ('classifier', LogisticRegression(max_iter=1000))])

In [74]:
# el parametro user_profile debe ser un diccionario con las claves age, education, marital.status, occupation, hours.per.week, sex, native.country
# (las predictoras seleeccionadas antes del split en test y train)
def recomendacion_profesional(user_profile):
    user_df = pd.DataFrame([user_profile]) # se pasa a dataframe el perfil del usuario recibido
    prediction = model.predict(user_df)[0]  # se hace prediccion -> prediccion == 1 = mas de 50K  | prediccion == 0 = no llegara a los 50K
    prob = model.predict_proba(user_df)[0][1]  # se predice la probabilidad y se guarda en variable 
    if prediction == 1:
        return f" Probabilidades de ganar más de 50K: {prob*100:.1f}%. Vas a ser rico, amigo."
    else:
        return f" Probabilidades de ganar más de 50K: {prob*100:.1f}%. Mejora tu perfil o cambia de oficio."

In [75]:
pablo = {
    "age": 28,
    "education": "Some-college",
    "marital.status": "Never-married",
    "occupation": "Prof-specialty",
    "hours.per.week": 40,
    "sex": "Male",
    "native.country": "Spain"
}

recomendacion_profesional(pablo) # pruebo conmigo mismo, estoy cooked

' Probabilidades de ganar más de 50K: 3.6%. Mejora tu perfil o cambia de oficio.'